// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4okgfI7NVq_rwsFslXPQi-5hAHcC03uk',
    appId: '1:49441798160:web:3bfd762edfa78dd9a6f295',
    messagingSenderId: '49441798160',
    projectId: 'legacy-vault-49a71',
    authDomain: 'legacy-vault-49a71.firebaseapp.com',
    storageBucket: 'legacy-vault-49a71.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYlgJey_ShjvzUpJGGJmY0EtbIJZUyZwo',
    appId: '1:49441798160:android:82c399889c8d744ca6f295',
    messagingSenderId: '49441798160',
    projectId: 'legacy-vault-49a71',
    storageBucket: 'legacy-vault-49a71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfQEOvRGcGC9z-2usb0kbDGZsKsmBgNm0',
    appId: '1:49441798160:ios:81bf73c5ac15ee7aa6f295',
    messagingSenderId: '49441798160',
    projectId: 'legacy-vault-49a71',
    storageBucket: 'legacy-vault-49a71.firebasestorage.app',
    iosBundleId: 'com.zenhor.legacyVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfQEOvRGcGC9z-2usb0kbDGZsKsmBgNm0',
    appId: '1:49441798160:ios:81bf73c5ac15ee7aa6f295',
    messagingSenderId: '49441798160',
    projectId: 'legacy-vault-49a71',
    storageBucket: 'legacy-vault-49a71.firebasestorage.app',
    iosBundleId: 'com.zenhor.legacyVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4okgfI7NVq_rwsFslXPQi-5hAHcC03uk',
    appId: '1:49441798160:web:d1641e77fab7ffe1a6f295',
    messagingSenderId: '49441798160',
    projectId: 'legacy-vault-49a71',
    authDomain: 'legacy-vault-49a71.firebaseapp.com',
    storageBucket: 'legacy-vault-49a71.firebasestorage.app',
  );

}